# Generated by Django 5.1.1 on 2024-09-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=100, verbose_name='URL'),
        ),
    ]
