# Generated by Django 5.1.1 on 2024-09-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_urls', '0002_alter_url_date_created_alter_url_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='video_id',
            field=models.CharField(max_length=32, null=True, verbose_name='Video ID'),
        ),
    ]
