# Generated by Django 5.1.1 on 2024-09-29 00:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('youtube_urls', '0003_url_video_id'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE youtube_urls_url
            SET video_id = SUBSTRING(url FROM 'v=([^&]+)');
            """,
            reverse_sql="""
            UPDATE youtube_urls_url
            SET video_id = NULL;
            """,
        ),
    ]
