# Generated by Django 5.1.1 on 2024-09-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_urls', '0004_auto_20240929_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='video_id',
            field=models.CharField(max_length=32, verbose_name='Video ID'),
        ),
    ]
